name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install venv according to poetry
        uses: 20c/workflows/poetry@v1

      - name: Deploy to GitHub Pages
        run: |
          poetry run mkdocs gh-deploy --force
