name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install according to poetry
        uses: grizz/workflow/poetry@v1

      - name: Run tests
        run: |
          poetry run mkdocs gh-deploy --force
